version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - run:
          name: update-ionic
          command: 'sudo yarn install -g ionic@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: 'cd ./ionic && yarn install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./ionic/node_modules
      - run:
          name: buildJIT
          command: 'cd ./ionic && yarn run ionic:build'
      - run:
          name: buildAOT
          command: 'cd ./ionic && yarn run ionic:build:prod'